before_script:
 - sudo apt-get install ant-optional
 - export OPTS="-server -Xmx3072M"
 - export JAVA_OPTS="${JAVA_OPTS} ${OPTS}"
 - export ANT_OPTS="${ANT_OPTS} ${OPTS}"
 - echo $JAVA_OPTS
 - echo $ANT_OPTS

addons:
  apt:
    packages:
      - openjdk-6-jdk

language: java
dist: trusty

# for gh-1388 (workaround for supporting test using OpenJDK 6)
matrix:
  include:
      env: 
        - JDK='OpenJDK 6'
        - TEST_SUITE=run_tests
      before_install:
        - echo "MAVEN_OPTS='-Dlicense.skip=true'" > ~/.mavenrc
        - TRAVIS_JDK_VERSION=openjdk6

jdk:
  - oraclejdk9
  - oraclejdk8
#  - oraclejdk7
#  - oraclejdk6

#  - openjdk9
  - openjdk8
  - openjdk7
# - openjdk6

env:
  - TEST_SUITE=run_tests
#  - TEST_SUITE=mathematics
#  - TEST_SUITE=numbers
#  - TEST_SUITE=search
#  - TEST_SUITE=sequences
#  - TEST_SUITE=strings
#  - TEST_SUITE=data_structures
#  - TEST_SUITE=sorts

script: "ant $TEST_SUITE"
